site_name: Araz Karimi
site_url: htttp://arzbrz.com
authors:
- Araz Bagherzadeh Karimi
nav:

- Home: index.md
-  Project Samples:  
   - 'Software': Background/BackgroundSoftware.md
   - 'Power': Background/BackgroundPower.md
  
- Courses: Courses.md

- Articles: Articles.md

- Project Request: ProjectRequest.md





theme:
    name: mkdocs
    nav_style: dark


